// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HackathonChatBotML.Model
{
    public class ModelInput
    {
        [ColumnName("ID"), LoadColumn(0)]
        public float ID { get; set; }


        [ColumnName("Category"), LoadColumn(1)]
        public string Category { get; set; }


        [ColumnName("Question"), LoadColumn(2)]
        public string Question { get; set; }


    }
}
